disable ci

diff --git a/.github/workflows/pr-ci-healchecks.yml b/.github/workflows/pr-ci-healchecks.yml
--- a/.github/workflows/pr-ci-healchecks.yml
+++ b/.github/workflows/pr-ci-healchecks.yml
@@ -40,26 +40,26 @@ jobs:
           OPEN_AI_API_KEY: ${{ secrets.OPEN_AI_API_KEY }}
         run: npx nx run-many -t lint,build,test --parallel=3 --skip-nx-cache --verbose
 
-      - name: Run E2E for Visor
-        id: visor-e2e-tests
-        continue-on-error: true
-        env:
-          OPEN_AI_API_KEY: ${{ secrets.OPEN_AI_API_KEY }}
-          SHINKAI_NODE_EXEC_PATH: ./apps/shinkai-visor-e2e/src/shinkai-node/shinkai_node_linux
-        run: |
-          chmod +x ./apps/shinkai-visor-e2e/src/shinkai-node/shinkai_node_linux
-          npx nx e2e shinkai-visor-e2e --verbose
-
-      - name: Upload playwright trace and videos
-        uses: actions/upload-artifact@v4
-        if: steps.visor-e2e-tests.outcome == 'failure'
-        with:
-          name: visor-e2e-results
-          path: ./apps/shinkai-visor-e2e/test-report/
-          retention-days: 1
-
-      - name: Fail when Visor E2E failed and reports were uploaded
-        if: steps.visor-e2e-tests.outcome == 'failure'
-        run: |
-          echo "Visor E2E failed"
-          exit 1
+#      - name: Run E2E for Visor
+#        id: visor-e2e-tests
+#        continue-on-error: true
+#        env:
+#          OPEN_AI_API_KEY: ${{ secrets.OPEN_AI_API_KEY }}
+#          SHINKAI_NODE_EXEC_PATH: ./apps/shinkai-visor-e2e/src/shinkai-node/shinkai_node_linux
+#        run: |
+#          chmod +x ./apps/shinkai-visor-e2e/src/shinkai-node/shinkai_node_linux
+#          npx nx e2e shinkai-visor-e2e --verbose
+#
+#      - name: Upload playwright trace and videos
+#        uses: actions/upload-artifact@v4
+#        if: steps.visor-e2e-tests.outcome == 'failure'
+#        with:
+#          name: visor-e2e-results
+#          path: ./apps/shinkai-visor-e2e/test-report/
+#          retention-days: 1
+#
+#      - name: Fail when Visor E2E failed and reports were uploaded
+#        if: steps.visor-e2e-tests.outcome == 'failure'
+#        run: |
+#          echo "Visor E2E failed"
+#          exit 1
